logging:
  level:
    "[io.github.resilience4j.circuitbreaker]": DEBUG

resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50 
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s 
        slow-call-rate-threshold: 50 
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 3s
    instances:
      products:
        base-config: defecto

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/login/oauth2/code/authorized
            scope:
            - openid
            - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: ms-oauth
            uri: lb://ms-oauth
            predicates:
            - Path=/api/security/**
            filters:
            - StripPrefix=2
          - id: ms-users
            uri: lb://ms-users
            predicates:
            - Path=/api/users/**
            filters:
            - StripPrefix=2
          #- id: ms-products
          #  uri: lb://ms-products
          #  predicates: 
          #  - Path=/api/products/**
            #- Header=token,\d+
            #- Header=token, 12345
            #- Method=GET, POST
            #- Query=color
            #- Cookie=color, azul
            #- Header=Content-Type, application/json
            #filters: 
            #- name: CircuitBreaker
            #  args:
            #    name: products
            #    statusCodes: 500
            #    fallbackuri: forward:/api/items/5
            #- StripPrefix=2
            #- name: EjemploCookie
            #  args:
            #    message: Hola mi mensaje personalizado para productos
            #    name: user
            #    value: Roy
          - id: ms-items
            uri: lb://ms-items
            predicates: 
            - Path=/api/items/**
            filters: 
            - StripPrefix=2
            - AddRequestHeader=token-request, dato1
            - AddResponseHeader=token-response, 12313123
            - AddRequestParameter=name, RoyW
            - SetResponseHeader=Content-Type, text/plain