spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: ms-products
            uri: lb://ms-products
            predicates: 
            - Path=/api/products/**
            #- Header=token,\d+
            #- Header=token, 12345
            #- Method=GET, POST
            #- Query=color
            #- Cookie=color, azul
            #- Header=Content-Type, application/json
            filters: 
            - StripPrefix=2
            - name: EjemploCookie
              args:
                message: Hola mi mensaje personalizado para productos
                name: user
                value: Roy
          - id: ms-items
            uri: lb://ms-items
            predicates: 
            - Path=/api/items/**
            filters: 
            - StripPrefix=2
            - AddRequestHeader=token-request, dato1
            - AddResponseHeader=token-response, 12313123
            - AddRequestParameter=name, RoyW
            - SetResponseHeader=Content-Type, text/plain