spring.application.name=ms-products
server.port=${PORT:0}
eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${random.value}

#Configurar MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_springboot_cloud
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Micrometer
management.tracing.sampling.probability=1.0
management.observations.http.server.requests.enabled=true
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}  %5p ${PID:- } --- [${spring.application.name:-}] [%15.15t] [%X{traceId}-%X{spanId}] %-40.40logger{39} : %m%n%wEx