services:
  eureka-server:
    container_name: eureka-server
    image: rwcalles/eureka:latest
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  #mysql-local:
  #  container_name: mysql-local
  #  image: mysql:8
  #  ports:
  #    - "3306:3306"
  #  restart: always
  #  networks:
  #    - springcloud
  #  environment:
  #    - MYSQL_DATABASE=db_springboot_cloud
  #    - MYSQL_ROOT_PASSWORD=admin
  #  volumes:
  #    - mysql_data:/var/lib/mysql
  ms-products:
    #container_name: ms-products
    image: rwcalles/products
    deploy:
      replicas: 1
    restart: always
    networks:
      - springcloud
    depends_on:
      - mysql-local
      - eureka-server
  ms-items:
    container_name: ms-items
    image: rwcalles/items
    restart: always
    ports:
      - "8005:8005"
    networks:
      - springcloud
    depends_on:
      - eureka-server
      - ms-products
networks:
  springcloud:

volumes:
  mysql_data: