spring.application.name=ms-items
server.port=8002

# Eliminamos, ya no se usa.
#spring.cloud.discovery.client.simple.instances.ms-products[0].uri=http://localhost:8001
#spring.cloud.discovery.client.simple.instances.ms-products[1].uri=http://localhost:9001

config.baseurl.endpoint.ms-products=http://ms-products

eureka.client.service-url.defaultZone=http://localhost:8761/eureka