spring.application.name=ms-items
server.port=8002

# Eliminamos, ya no se usa.
#spring.cloud.discovery.client.simple.instances.ms-products[0].uri=http://localhost:8001
#spring.cloud.discovery.client.simple.instances.ms-products[1].uri=http://localhost:9001

#config.baseurl.endpoint.ms-products=http://ms-products
config.baseurl.endpoint.ms_products=http://ms-products

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

## RESILIENCE4J - CONFIGURACION EN ARCHIVO PROPERTY
#resilience4j.circuitbreaker.configs.defecto.sliding-window-size=6
#resilience4j.circuitbreaker.configs.defecto.failure-rate-threshold=50
#resilience4j.circuitbreaker.configs.defecto.wait-duration-in-open-state=20s
#resilience4j.circuitbreaker.configs.defecto.permitted-number-of-calls-in-half-open-state=4
#resilience4j.circuitbreaker.configs.defecto.slow-call-rate-threshold=50
#resilience4j.circuitbreaker.configs.defecto.slow-call-duration-threshold=2s
#resilience4j.circuitbreaker.instances.items.base-config=defecto
 
#resilience4j.timelimiter.configs.defecto.timeout-duration=2s
#resilience4j.timelimiter.instances.items.base-config=defecto

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
management.observations.http.server.requests.enabled=true
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}  %5p ${PID:- } --- [${spring.application.name:-}] [%15.15t] [%X{traceId}-%X{spanId}] %-40.40logger{39} : %m%n%wEx

logging.level.io.micrometer.tracing=DEBUG
logging.level.brave=DEBUG
logging.level.org.springframework.boot.actuate.autoconfigure=DEBUG