spring.application.name=ms-oauth
server.port=9100
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
management.observations.http.server.requests.enabled=true
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}  %5p ${PID:- } --- [${spring.application.name:-}] [%15.15t] [%X{traceId}-%X{spanId}] %-40.40logger{39} : %m%n%wEx