spring.application.name=eureka-server
server.port=8761

# Solo servira como servidor de nombre
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Aumenta el tiempo que un nodo espera para leer datos de otro (en milisegundos)
eureka.server.peer-node-read-timeout-ms=2000

# Aumenta el tiempo que un nodo espera para establecer la conexión inicial
eureka.server.peer-node-connect-timeout-ms=2000